export default {
  RESTAURANT_ALL_PENDING: "RESTAURANT_ALL_PENDING",
  RESTAURANT_ALL_REJECTED: "RESTAURANT_ALL_REJECTED",
  RESTAURANT_ALL_FULFILLED: "RESTAURANT_ALL_FULFILLED",

  SIGNUP_USER_PENDING: "SIGNUP_USER_PENDING",
  SIGNUP_USER_REJECTED: "SIGNUP_USER_REJECTED",
  SIGNUP_USER_FULFILLED: "SIGNUP_USER_FULFILLED",

  SIGNOUT_USER_PENDING: "SIGNOUT_USER_PENDING",
  SIGNOUT_USER_REJECTED: "SIGNOUT_USER_REJECTED",
  SIGNOUT_USER_FULFILLED: "SIGNOUT_USER_FULFILLED"
};
