export default {
  RESTAURANT_ALL_PENDING: "RESTAURANT_ALL_PENDING",
  RESTAURANT_ALL_REJECTED: "RESTAURANT_ALL_REJECTED",
  RESTAURANT_ALL_FULFILLED: "RESTAURANT_ALL_FULFILLED",

  RESTAURANT_DETAILS_PENDING: "RESTAURANT_DETAILS_PENDING",
  RESTAURANT_DETAILS_REJECTED: "RESTAURANT_DETAILS_REJECTED",
  RESTAURANT_DETAILS_FULFILLED: "RESTAURANT_DETAILS_FULFILLED",

  RESTAURANT_PHOTOS_PENDING: "RESTAURANT_PHOTOS_PENDING",
  RESTAURANT_PHOTOS_REJECTED: "RESTAURANT_PHOTOS_REJECTED",
  RESTAURANT_PHOTOS_FULFILLED: "RESTAURANT_PHOTOS_FULFILLED",

  SET_KEYWORD: "SET_KEYWORD"
};
