export default {
  SIGNIN_USER_PENDING: "SIGNIN_USER_PENDING",
  SIGNIN_USER_REJECTED: "SIGNIN_USER_REJECTED",
  SIGNIN_USER_FULFILLED: "SIGNIN_USER_FULFILLED",

  SIGNUP_USER_PENDING: "SIGNUP_USER_PENDING",
  SIGNUP_USER_REJECTED: "SIGNUP_USER_REJECTED",
  SIGNUP_USER_FULFILLED: "SIGNUP_USER_FULFILLED",

  SIGNOUT_USER_PENDING: "SIGNOUT_USER_PENDING",
  SIGNOUT_USER_REJECTED: "SIGNOUT_USER_REJECTED",
  SIGNOUT_USER_FULFILLED: "SIGNOUT_USER_FULFILLED",

  GET_USER_LOCATION_PENDING: "GET_USER_LOCATION_PENDING",
  GET_USER_LOCATION_REJECTED: "GET_USER_LOCATION_REJECTED",
  GET_USER_LOCATION_FULFILLED: "GET_USER_LOCATION_FULFILLED"
};
